name: iOS SDK CI

on:
  push:
    branches:
      - main  # Change if your default branch is different
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Run Unit Tests
        run: |
          cd Example
          xcodebuild test -workspace DemoApp.xcworkspace -scheme DemoApp -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' | xcpretty

      - name: Upload Test Results (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ~/Library/Developer/Xcode/DerivedData
