name: iOS SDK CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 15.3
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'

      - name: Show selected Xcode (debug)
        run: |
          xcode-select -p
          xcodebuild -version

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build & Run iOS SDK Tests
        run: |
          set -o pipefail
          xcodebuild clean build test \
            -scheme Coralogix-Package \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
          | xcpretty

