name: Podspec Lint

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.podspec'
      - '.github/workflows/podspec-lint.yml'
  push:
    branches: [ master ]
    paths:
      - '**/*.podspec'
      - '.github/workflows/podspec-lint.yml'

jobs:
  lint:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Xcode 15.4 (iOS 17.5 sim available)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install CocoaPods
        run: |
          gem install cocoapods -v 1.16.2 --no-document
          pod --version

      - name: Print environment
        run: |
          set -e
          xcodebuild -version
          ruby -v
          pod env

      # Lint CoralogixInternal (base pod)
      - name: Lint CoralogixInternal.podspec
        run: |
          set -euo pipefail
          echo "🔍 Linting CoralogixInternal.podspec (iOS, static frameworks)…"
          pod lib lint CoralogixInternal.podspec \
            --platforms=iOS \
            --use-static-frameworks \
            --skip-tests \
            --fail-fast \
            --no-clean \
            --verbose 2>&1 | tee lint_internal.log
          echo "✅ CoralogixInternal.podspec passed lint."

      - name: Show Internal lint error summary (if any)
        if: failure()
        run: |
          echo "---- First error in Internal lint log ----"
          awk '/❌/{flag=1} flag{print; if (/^$/) exit}' lint_internal.log || true
          echo "-----------------------------------------"

      # Lint SessionReplay (depends on Internal)
      - name: Lint SessionReplay.podspec
        run: |
          set -euo pipefail
          echo "🔍 Linting SessionReplay.podspec (iOS, static frameworks, includes Internal)…"
          pod lib lint SessionReplay.podspec \
            --include-podspecs=CoralogixInternal.podspec \
            --platforms=iOS \
            --use-static-frameworks \
            --skip-tests \
            --fail-fast \
            --no-clean \
            --verbose 2>&1 | tee lint_session_replay.log
          echo "✅ SessionReplay.podspec passed lint."

      - name: Show SessionReplay lint error summary (if any)
        if: failure()
        run: |
          echo "---- First error in SessionReplay lint log ----"
          awk '/❌/{flag=1} flag{print; if (/^$/) exit}' lint_session_replay.log || true
          echo "-----------------------------------------------"

      # Lint Coralogix (depends on Internal)
      - name: Lint Coralogix.podspec
        run: |
          set -euo pipefail
          echo "🔍 Linting Coralogix.podspec (iOS, static frameworks, includes Internal)…"
          pod lib lint Coralogix.podspec \
            --include-podspecs=CoralogixInternal.podspec \
            --platforms=iOS \
            --use-static-frameworks \
            --skip-tests \
            --fail-fast \
            --no-clean \
            --verbose 2>&1 | tee lint_main.log
          echo "✅ Coralogix.podspec passed lint."

      - name: Show Coralogix lint error summary (if any)
        if: failure()
        run: |
          echo "---- First error in Coralogix lint log ----"
          awk '/❌/{flag=1} flag{print; if (/^$/) exit}' lint_main.log || true
          echo "-------------------------------------------"

      # Upload logs for debugging
      - name: Upload lint logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: podspec-lint-logs
          path: |
            lint_internal.log
            lint_session_replay.log
            lint_main.log
          if-no-files-found: ignore
